FROM --platform=linux/amd64 ubuntu:22.04 AS builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git ruby

COPY . /repo
WORKDIR /repo
RUN make -j8 out/whirl

FROM ubuntu:22.04 AS package
COPY --from=builder /repo/out/whirl /
